@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.ceramics.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
